=== AFactor/Raml/Taxonomy/v1.0d/Schemas/taxonomy.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "additionalProperties":false,
  "required": false,
  "properties": {
    "children": {
      "type": "array",
      "required": false,
      "items": {
        "$ref": "taxonomy.json",
        "description": "Self referencing taxonomy node",
        "required": false
      }
    },
    "id": {
      "type": "string",
      "description": "Node id",
      "required": true
    },
    "levelName": {
      "type": "string",
	  "description": "Node depth level. Eg root,superdepartment, department, aisle, shelf",
      "required": true
    },
    "nodeName": {
      "type": "string",
      "required": true
    }
  }
}

=== AFactor/Raml/taxonomy/v1.0/examples/taxonomies.json
{
  "nodeName": "Root",
  "id": "Root",
  "levelName": "Root",
  "children": [
    {
      "nodeName": "Fresh Food",
      "id": "TO_1284175199",
      "levelName": "SuperDepartment",
      "children": [
        {
          "nodeName": "Fresh Fruit",
          "id": "TO_02038179352",
          "levelName": "Department",
          "children": [
            {
              "nodeName": "Apples, Pears & Rhubarb",
              "id": "TO_1794209734",
              "levelName": "Aisle",
              "children": [
                {
                  "nodeName": "Cooking Apples",
                  "id": "TO_0703061265",
                  "levelName": "Shelf"
                },
                {
                  "nodeName": "Red/Pink Eating Apples",
                  "id": "TO_1626390530",
                  "levelName": "Shelf"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
